apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic-visits-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: petclinic
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/tanzu-end-to-end/spring-petclinic-microservices
      ref:
        branch: master
  # build:
  #   env:
  #   - name: BP_MAVEN_BUILT_MODULE
  #     value: spring-petclinic-visits-service